# Generated by Django 4.2.11 on 2024-03-16 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=10, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Наименование')),
                ('brief_name', models.CharField(max_length=10, verbose_name='Краткое наименование')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Продолжительность')),
                ('level', models.IntegerField(choices=[(0, 'Среденнее образование'), (1, 'Бакалавриат'), (2, 'Магистратура'), (3, 'Специалитет')], verbose_name='Уровень образования')),
                ('language', models.IntegerField(choices=[(0, 'Русский'), (1, 'Английский')], verbose_name='Язык обучения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('zet', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(361)], verbose_name='ЗЕТ')),
            ],
        ),
    ]
